### ISSUE TITLE
wasm bug

### ISSUE THREAD

**Issue by gmamekudz** [eshaz/wasm-audio-decoders#106]
in MPEGDecoder.js, I have to change the code to this:

  this.reset = () => {
    if(this._common)this.free();
    return this._init();
  };

By importing multiple mp3 sounds, there will be a undefined-error after loading more than 5 files.

**Comment by eshaz** [comment]
Could you try to reproduce this in the demo page or in a unit test, or give a code example of what you're trying to do?

There's not enough info here for me to help.

**Comment by eshaz** [comment]
Closing due to no response.
