### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'bind' [of "this.bt.M"]) @1.2.4

### ISSUE THREAD

**Issue by NHQ** [eshaz/wasm-audio-decoders#22]
I tried upgrading to 1.2.4.  

Firefox says: Uncaught (in promise) TypeError: this.bt.M is undefined

Tested in latest Chrome, also Chromium and FF.

**Comment by NHQ** [comment]
Yes, I am using ogg-opus-decoder.   Is there a non-minified version in the NPM release?

**Comment by eshaz** [comment]
You can import the package as an ECMAScript module to use the non-minified version. I'll take a look at this and try to reproduce it with the minified version.

**Comment by NHQ** [comment]
I used the regular version in /dist.  I get two errors in FF.  The second one maybe more useful:
```Uncaught (in promise) TypeError: this._WASMAudioDecoderCommon.initWASMAudioDecoder is undefined```
From line # 10424:
```js
this._common = await this._WASMAudioDecoderCommon.initWASMAudioDecoder.bind(        this
      )();
```

The first error is ```Uncaught (in promise) TypeError: this.bt.M is undefined``` and points to line 21751, which a is a minified string even in the unminified version.

**Comment by eshaz** [comment]
I wasn't able to reproduce this on the [demo page](https://eshaz.github.io/wasm-audio-decoders/) nor in the test suite. Everything worked fine with the included minified build.

**Comment by NHQ** [comment]
I got it.  I was still passing an args object to the constructor ({onDecode, etc}).  That interfered with the [default params](https://github.com/eshaz/wasm-audio-decoders/blob/master/src/ogg-opus-decoder/src/OggOpusDecoder.js#L6).

**Comment by eshaz** [comment]
The options parameter in the constructor was removed as a breaking change when [ogg-opus-decoder/1.0.0](https://github.com/eshaz/wasm-audio-decoders/releases/tag/ogg-opus-decoder%2F1.0.0) was released. This project follows semantic versioning where a major version increment indicates a breaking change. It's always good practice to read through the release documentation when upgrading major versions.
