### ISSUE TITLE
Decoded Audio is longer than real audio.

### ISSUE THREAD

**Issue by NHQ** [eshaz/wasm-audio-decoders#23]
In my tests, I check the time elapsed between decoded frames and compare it to the length of the real decoded audio.  I am getting longer audio buffers than the total elapsed time.  (Elapsed time = real-time, i.e. live recording + encoding + network latency + decoding.) 

The reason I checked in the first place is b/c my app has a creeping latency I could not otherwise debug or buffer.  The tests seem to prove the audio is actually getting longer (not latency). 

***I don't know if the source of this bug is the decoder or the encoder.***  I will have to do some tests to determine.  What do you use to encode ogg?

**Comment by eshaz** [comment]
In the unit tests, I used ffmpeg to encode the test file to Ogg Opus. This library doesn't support encoding at all. `ogg-opus-decoder` pretty much just a wrapper for `libopusfile`, but with only decoding enabled.

**Comment by eshaz** [comment]
Closing this issue since it has received no response.

`ogg-opus-decoder` has recieved a few version bumps since this issue was opened, please try out the latest version and see if that helps.

If this is still happening for you, please reopen the issue with at lease one example with the compressed and expected decoded file so I can investigate.

**Comment by haywirez** [comment]
I found similar problems while testing. A file that should have `62728` decoded frames gets `63048`. My best guess is some glitch regarding handling pre-skip or not discarding potential padding frames at the end. Still investigating, unfortunately the repo tests don't build or run for me out of the box.

Manual reproduction: encoding a deliberately weird, 1.306833 seconds long [what.wav](https://cdn.haywirez.com/file/haywirez-cdn/ogg-opus-test/what.wav) using both ffmpeg and and libopus' / opus-tools provided opusenc: 

`ffmpeg -i what.wav -c:a libopus -b:a 128k -o what-ffmpeg.opus` = [what-ffmpeg.opus](https://cdn.haywirez.com/file/haywirez-cdn/ogg-opus-test/what-ffmpeg.opus) 
`opusenc --bitrate 128 ./what.wav what-opusenc.opus` = [what-opusenc.opus](https://cdn.haywirez.com/file/haywirez-cdn/ogg-opus-test/what-opusenc.opus)

(both yield the wrong `samplesDecoded: 63048`)

Just to double check, I also decoded the opus files using cli tools back to .wav (ffmpeg and opusdec). Resulting sample lengths according to sox are all consistently rounded: `soxi -s what.wav`, `soxi -s what-ffmpeg.opus` `soxi -s what-ffmpeg.opus` = `62728`. 

This also corresponds to the better reported duration x sampling rate of the PCM data = `Math.round(1.3068333*48000)` if duration is extracted using let's say ffprobe:

`ffprobe -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 what.wav 2>/dev/null`

**Comment by eshaz** [comment]
@haywirez Thanks for providing some examples. I'll take a look at this too. Let me know if you find anything.

**Comment by eshaz** [comment]
I think I found the issue. In the Ogg container format for Opus streams, the [`absoluteGranulePosition`](https://wiki.xiph.org/OggOpus#Granule_Position) in the header indicates the total PCM samples within an Ogg packet. At the end of a stream, the decoder should trim out any extra samples at the end of the packet according to the total samples indicated in`absoluteGranulePosition`. `ogg-opus-decoder` isn't trimming the extra samples in this case and is returning everything that libopus decodes. This seems to be a few hundred samples in practice, which is not much, but it makes a difference nonetheless.

I'll get a release published soon for `ogg-opus-decoder`.

This issue probably also exists in `flac-decoder` and `ogg-vorbis-decoder` in this repo, which have the same logic for parsing the Ogg stream. I'll take a look at these as well.

**Comment by eshaz** [comment]
I've published a release of [`ogg-opus-decoder`](https://github.com/eshaz/wasm-audio-decoders/releases/tag/ogg-opus-decoder%2F1.6.2) that should fix this. I'll keep this issue open so I can continue to work on the other libraries that demux from Ogg. Let me know if this fixes your issue.
