### ISSUE TITLE
Can you support wav and flac decoder?

### ISSUE THREAD

**Issue by kaneruan** [eshaz/wasm-audio-decoders#54]
I search wav and flac in npm.com long time. 
But haven't searched. 
If you can support them, I will appreciate that,

**Comment by eshaz** [comment]
I have plans to add additional codecs like FLAC, Vorbis, and AAC. I'll probably get around to adding those around October.

For WAV, this format is actually not compressed so there is nothing to decode. However, I may consider adding a "decoder" that translates this format into the same output that the other decoders produce. This may be useful if someone wants to play WAV data using the WebAudio api.

**Comment by githubmann** [comment]
thank you

**Comment by eshaz** [comment]
Added [@wasm-audio-decoders/flac](https://www.npmjs.com/package/@wasm-audio-decoders/flac) in #58
