### ISSUE TITLE
Streamable?

### ISSUE THREAD

**Issue by robclouth** [eshaz/wasm-audio-decoders#56]
Is it possible to keep the decoder open and pass it blocks of data as they come in? I'd like to download a file and decode it as a stream if possible. Thanks

**Comment by eshaz** [comment]
Yes, it is possible, and one of the main features of this library. You can stream by passing in each chunk of data into the `decode` method. This can also be done concurrently using the Web Worker implementation. When you want to decode another file, call the decoder's `reset` method.

The README for each decoder has more information and a few examples.

I use this functionality in my other library, [icecast-metadata-player](https://github.com/eshaz/icecast-metadata-js), to play compressed streaming audio through the Web Audio API.
