### ISSUE TITLE
[ogg-opus-decoder] Support different input sample rates?

### ISSUE THREAD

**Issue by aleclarson** [eshaz/wasm-audio-decoders#65]
I don't have a hard requirement for different sample rates atm, but it could be a nice option for mobile devices with spotty connections?

**Comment by eshaz** [comment]
Opus is only able to be decoded at 48 kHz, and it's not possible within standard Opus to decode to any other sample rates. Any resampling should be done after the audio has been decoded. See: https://wiki.xiph.org/OpusFAQ#How_do_I_use_44.1_kHz_or_some_other_sampling_rate_not_directly_supported_by_Opus.3F

Regardless of the sample rate limitation, Opus is an excellent codec for latency and low bitrates. I would go so far as to say it is objectively the best lossy audio codec there is to date.

To find an acceptable bitrate, you can run a few tests by encoding some audio with bitrates that seem lower than usual (i.e. compared to MP3 or AAC) and listen to what sounds good to you. I've personally found that music sounds transparent at around 90-100kb/s and speech is understandable at bitrates as low as 10kb/s.

If you want to resample the audio after it's been decoded, you can use the `OfflineAudioContext` natively in the browser. See: https://gist.github.com/jhiswin/b88ecf7900b76810429b I'm sure there are some high quality resampler libraries out there too as well for Web or NodeJS use.
