### ISSUE TITLE
[ogg-opus-decoder] compile error in Safari 16

### ISSUE THREAD

**Issue by canove** [eshaz/wasm-audio-decoders#66]
Hello and thanks for this awesome lib!

ogg-opus-decoder works fine in Chrome and Firefox, but not in Safari. It throws a CompileError: `WebAssembly.Module doesn't parse at byte 0`

Is there anything I can do to get around this, or is it really a Safari limitation?

Thanks anyway! 

![image](https://user-images.githubusercontent.com/24817866/210630786-a0b5b188-3496-45bf-aef8-0e611a646a56.png)

**Comment by eshaz** [comment]
I'm not able to reproduce this on my side. Are you using some minifier that's doing something different for Safari?

**Comment by canove** [comment]
It's a React app that uses [VITE](https://vitejs.dev/) to build. 

Indeed, [demo page](https://eshaz.github.io/wasm-audio-decoders/) works normally.

I will try to get more information, thanks!

**Comment by canove** [comment]
Just figured it out. My page was missing  `<meta charset="UTF-8" />` on index.html

I think it was messing up with your WASM string or something! Every other browser works great, just Safari broke!

Thanks anyway.

**Comment by eshaz** [comment]
Great find! That one probably wouldn't have occurred to me.

The WASM string uses [`simple-yenc`](https://github.com/eshaz/simple-yenc) to encode the binary, which is more efficient than base64. This would definitely cause issues if the browser's character set was doing something different than utf-8.

I'll add a note in the documentation about this.
