### ISSUE TITLE
Opus decoder assumes 48kHz sample rate/missing libFLAC config.h

### ISSUE THREAD

**Issue by setdebug** [eshaz/wasm-audio-decoders#73]
I want to decode and play 8kHz opus frames. It doesn't appear to be possible to set the sample rate of the decoder without modifying the `opus_multistream_decoder_create()` call in `src/opus-decoder/src/opus_frame_decoder.c`.

I am trying to modify that file and build, but it seems that `config.h` for libFLAC is missing. Am I supposed to be configuring and building the dependencies with cmake first?

```
Building FLAC Emscripten Library tmp/flac.bc...
modules/flac/src/libFLAC/stream_decoder.c:34:12: fatal error: 'config.h' file not found
#  include <config.h>
           ^~~~~~~~~~
1 error generated.
```

**Comment by eshaz** [comment]
You might try running `make libopus-configure` and then `make opus-decoder` and that should only build the wasm for opus-decoder.

Opus only supports encoding and decoding at 48kHz with the standard codec. You might just be better off using 48kHz. See https://github.com/eshaz/wasm-audio-decoders/issues/65#issuecomment-1364454562

**Comment by setdebug** [comment]
The audio frames I am trying to decode are encoded at 8kHz (NB speech) - unless I'm mistaken, the decoder has to be run with the same sample rate as the encoder was. The issue I ran into is the audio is unintelligible and plays extremely fast (6x seems about right).

I was able to get it to build and it produced `opus-decoder.js`; however, when the web worker is created, I get an error.

The script is included in the HTML file like this:
```
<script src="opus-decoder.js"></script>
```

The web worker is created like this:
```
state.decoder = new window["opus-decoder"].OpusDecoderWebWorker();
```

(which worked fine with the opus-decoder.js from your repository)

Here's the console output:
```
Uncaught (in promise) ReferenceError: buffer is not defined
    at e31ca22f-bd35-403c-a6f7-918dd9cb36a9:800:16
```

```
  this.instantiate = () => {
    this.getModule().then((wasm) => WebAssembly.instantiate(wasm, imports)).then((instance) => {
      var asm = instance.exports;
   _opus_frame_decoder_create = asm["g"];
   _malloc = asm["h"];
   _opus_frame_decode_float_deinterleaved = asm["i"];
   _opus_frame_decoder_destroy = asm["j"];
   _free = asm["k"];
   asm["l"];
   wasmMemory = asm["e"];
   updateMemoryViews();
   initRuntime(asm);
   ready();
  });

  this.ready = new Promise(resolve => {
   ready = resolve;
  }).then(() => {
   this.HEAP = buffer;            <<<--- error here
   this._malloc = _malloc;
   this._free = _free;
   this._opus_frame_decoder_create = _opus_frame_decoder_create;
   this._opus_frame_decode_float_deinterleaved = _opus_frame_decode_float_deinterleaved;
   this._opus_frame_decoder_destroy = _opus_frame_decoder_destroy;
  });
  return this;
  };})
```

I was able to install emscripten 2.0.34 with emsdk, but the configure or compile failed (I should have saved the errors). I installed the latest version and everything appeared to work (except for the in-browser runtime error, obviously).

Thanks for your help.

**Comment by eshaz** [comment]
I'm not sure what would cause this. Do you have a fork / branch you're working on? If so I could take a look.
