### ISSUE TITLE
Error running mpg123-decoder inside new worker.

### ISSUE THREAD

**Issue by ergcode** [eshaz/wasm-audio-decoders#81]
node -v 18.16.0
"mpg123-decoder": "^0.4.7"

Hello! I'm trying to run multiple processes through worker_threads. Which should perform the analysis of mp3 files.
And I get an error from the @eshaz/web-worker module:
```
code@ergonomic ~/dev/listener/.tmp $ node worker.js 
worker online
some data
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Module.require (node:internal/modules/cjs/loader:1134:3)
    at require (node:internal/modules/cjs/helpers:110:18)
    at workerThread (/home/code/dev/radio/listener/node_modules/@eshaz/web-worker/cjs/node.js:188:9)
    at Object.<anonymous> (/home/code/dev/radio/listener/node_modules/@eshaz/web-worker/cjs/node.js:67:56)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Code example:
```
'use strict';


import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);


(async () => {
	try {
		if (isMainThread) {
			const worker = new Worker(
				__filename,
				{
					workerData: `some data`,
				}
			);
			worker
				.on(`message`, (message) => console.log(message))
				.on(`online`, () => console.log(`worker online`))
				.on(`error`, (err) => console.error(err));


		} else {
			console.log(workerData);
			const { MPEGDecoder } = await import('mpg123-decoder');
			const decoder = new MPEGDecoder();
			await decoder.ready;
		}

	} catch (error) {
		console.error(error);
		process.exit();
	}
})();
```

Tell me, how can I eliminate the conflict of several worker_threads (my module and yours)?

**Comment by eshaz** [comment]
Could you use [`MPEGDecoderWorker`](https://github.com/eshaz/wasm-audio-decoders/tree/master/src/mpg123-decoder#mpegdecoderwebworker) for this, rather than wrapping the decoder in your own worker code?

**Comment by eshaz** [comment]
When is the error happening? When you import or when you execute the decoder?

I'm not sure what you mean by separate the worker_threads. Are you finding that something's being set globally?

The built in worker implementation is pretty fast. I have some caching that reuses the compiled WASM and worker source code that you can't do with the main thread instance. I would doubt that the event loop will be the bottleneck. Have you run any tests to see where your bottleneck is?

**Comment by ergcode** [comment]
> When is the error happening? When you import or when you execute the decoder?
> 
> I'm not sure what you mean by separate the worker_threads. Are you finding that something's being set globally?
> 
> The built in worker implementation is pretty fast. I have some caching that reuses the compiled WASM and worker source code that you can't do with the main thread instance. I would doubt that the event loop will be the bottleneck. Have you run any tests to see where your bottleneck is?

The error occurs:
- When declaring a module inside a function.
const { MPEGDecoder } = await import('mpg123-decoder');
- Or when declaring a module in the file scope.
import { MPEGDecoder } from 'mpg123-decoder';
If I run the code in the sub-process worker_threads.

Your mp3 parsing implementation is the fastest one in npm. Since it does not require a call to child_process exec. 10 times faster in tests. There are no problems here. You and the author of mpg123 are geniuses.

On 4770k + 16 GB RAM, I can analyze up to 200 audio streams at the same time (with analysis of the received data). If I increase the memory to 32 GB of RAM, I can process 400 threads. So there are no performance issues for sure.

I only created this ticket because my module's worker_threads conflicted with your module's worker_threads. If you do not have an answer, then I will try to solve this problem on my own with a subsequent proposal for changes.

I apologize, as I write through a translator and in some places it is difficult to understand me.

**Comment by eshaz** [comment]
Thanks for the complement on the performance!

I'm not sure what's happening to cause there this issue. The worker code shouldn't be executed when the module is imported, other than a platform check to determine if the environment is Node or a browser.

Feel free to submit a PR, or reply here if you find anything. I'll take a look and try to reproduce it on my side.

**Comment by eshaz** [comment]
I just released a new version of [`mpg123-decoder`](https://github.com/eshaz/wasm-audio-decoders/releases/tag/mpg123-decoder%2F0.4.8) that should fix this. I also added a test case for this that is based on your example. Let me know if you're still facing this issue.

**Comment by ergcode** [comment]
It helped a lot!

I temporarily used the "node:cluster" module and got 4-7% CPU usage while listening to 36 streams (mp3, 2 channels, 22050).
After you made the changes and I reconnected the "node:worker_threads" module, the load dropped to 1-2%, and the RAM consumption also decreased slightly.
Thank you for your help!

Your module decodes 200 streams per second at an incredible speed without causing significant load.

Later, I will ask the customer to support your project.
