### ISSUE TITLE
Ogg Vorbis random noises in decoded audio

### ISSUE THREAD

**Issue by Zokhoi** [eshaz/wasm-audio-decoders#82]
In my use case I have a bunch of ogg files, some of them decode to have random noises throughout the audio, while also having the decoded audio shorter than expected.

![image](https://github.com/eshaz/wasm-audio-decoders/assets/20432565/6ce03dcd-4952-43cb-9080-e63f07de5547)
Upper: audio decoded with the ogg vorbis decoder
Lower: ogg file imported into Audacity directly

[Here](https://www.zokhoi.com/files/Chronostasis/back1.ogg) is the offending source audio file used for the example screenshot.

Code to produce the decoded audio:
```js
import fs from "fs";
import path from "path";
import { OggVorbisDecoder } from "@wasm-audio-decoders/ogg-vorbis";
import wav from "node-wav";

/** Reads filename from command line input */
let filename = process.argv[2];
let dir = path.dirname(path.resolve(filename));

!(async ()=>{  
  let decoder = new OggVorbisDecoder();
  await decoder.ready;

  let fileBuf = fs.readFileSync(filename);
  let audio = await decoder.decodeFile(fileBuf);

  let buf = wav.encode(audio.channelData, {
    sampleRate: audio.sampleRate,
    float: true,
    bitDepth: audio.bitDepth,
  });
  fs.writeFileSync(path.resolve(dir, `test.wav`), buf);

  decoder.free();
})()
```

All ogg files in my collection should have been generated by the same encoder, because the collection was a pack of samples making up one entire song. However, only some of the files have this issue. The whole pack is available [here](https://manbow.nothing.sh/event/event.cgi?action=More_def&num=252&event=110) ([google drive](https://drive.google.com/file/d/0B-lINouU2qRNQWpfemZCYXh6aXc)).

**Comment by eshaz** [comment]
Thanks for posting this. I'll take a look. Which encoder are you using to write the Ogg Vorbis files?

**Comment by Zokhoi** [comment]
I didn't make the ogg files so I don't know the encoder fot them. For saving the wave files in the sample code it was node-wav.

**Comment by eshaz** [comment]
I found the issue for this. There is a bug in the `codec-parser` Ogg parsing where if there are two continued packets in a row, the previous data is not appended. The `else if` condition below should be moved to an `if` condition above it, so the previous packet data is saved. I'll get a release published for `codec-parser` and all the other libraries that rely on it published here soon.

https://github.com/eshaz/codec-parser/blob/master/src/containers/ogg/OggParser.js#L129-L145

This could happen to any codec using Ogg, but it doesn't seem very common to have a bunch of continued packets in a row like in the example you provided. It's still valid Ogg Vorbis, just unusual. Thanks for reporting this and providing a good example.

**Comment by eshaz** [comment]
I just published a new release of [`@wasm-audio-decoders/ogg-vorbis`](https://github.com/eshaz/wasm-audio-decoders/releases/tag/ogg-vorbis%2F0.1.6). Testing locally worked just fine and looked just like your screenshot in Audacity. Let me know if something still isn't working.
