### ISSUE TITLE
Ogg Vorbis decoding TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Zokhoi** [eshaz/wasm-audio-decoders#84]
Ok some of these ogg vorbis files just error out when decoding. Same sample code from #82 .
Audacity and VLC can load them fine.

Sample files: [1](https://www.zokhoi.com/files/Mobilys/b_piano_v84l8o5ap.ogg) [2](https://www.zokhoi.com/files/Mobilys/b_piano_v84l8o6ap.ogg) [3](https://www.zokhoi.com/files/Random/b_Kick_v80o5d.ogg)

Error log:
```
file:///media/data/GitHub/bmstem/node_modules/.pnpm/@wasm-audio-decoders+ogg-vorbis@0.1.6/node_modules/@wasm-audio-decoders/ogg-vorbis/src/OggVorbisDecoder.js:74
    this._input.buf.set(data);
                    ^

TypeError: Cannot convert undefined or null to object
    at Uint8Array.set (<anonymous>)
    at Decoder.sendSetupHeader (file:///media/data/GitHub/bmstem/node_modules/.pnpm/@wasm-audio-decoders+ogg-vorbis@0.1.6/node_modules/@wasm-audio-decoders/ogg-vorbis/src/OggVorbisDecoder.js:74:21)
    at OggVorbisDecoder.decodeOggPages (file:///media/data/GitHub/bmstem/node_modules/.pnpm/@wasm-audio-decoders+ogg-vorbis@0.1.6/node_modules/@wasm-audio-decoders/ogg-vorbis/src/OggVorbisDecoder.js:228:27)
    at OggVorbisDecoder.decodeFile (file:///media/data/GitHub/bmstem/node_modules/.pnpm/@wasm-audio-decoders+ogg-vorbis@0.1.6/node_modules/@wasm-audio-decoders/ogg-vorbis/src/OggVorbisDecoder.js:255:26)
    at file:///media/data/GitHub/bmstem/test.js:15:29
```

Full file packs: [Dachs - MOBILYS](https://manbow.nothing.sh/event/event.cgi?action=More_def&num=24&event=127), [Sobrem x Silentroom - Random](https://manbow.nothing.sh/event/event.cgi?action=More_def&num=372&event=137)

**Comment by eshaz** [comment]
Thanks for another good test case. I found the error in this one as well, which is again with the `codec-parser` library. I'll cut a release soon to fix this.

Do you have any other cases that are failing for you? If so, can you post all them them in a single issue, that way I can fix them all in a single release.

**Comment by Zokhoi** [comment]
Nothing more that I can find at the moment. My use case is related to a [script](https://github.com/Qrael/bmx2stems) that parses through existing [bms-formatted rhythm game charts](https://bmssearch.net), so I could try to get hold of as much charts that used ogg files as there are in the wild for testing with though.

**Comment by eshaz** [comment]
Sounds good. If you want to take the time to do that, I would appreciate it, but you've been very helpful so far on finding good examples. I'll go ahead and release the fix that solves this issue. If you run into any more problems, let me know.
