### ISSUE TITLE
trouble with some oggs

### ISSUE THREAD

**Issue by weepy** [eshaz/wasm-audio-decoders#86]
I've shared an ogg file here It's called metronome2.ogg

I get the following error log

<img width="522" alt="Screenshot 2023-08-02 at 14 26 00" src="https://github.com/eshaz/wasm-audio-decoders/assets/820/f9b3d623-037b-4bf6-b789-9fce0a090fdf">

File here => 
https://drive.google.com/file/d/1MoTPQnnuzLiVw_c9b0p_e12b3H1ilTlU/view?usp=sharing

**Comment by eshaz** [comment]
Thanks for the example. I'll take a look.

**Comment by eshaz** [comment]
I just published a release that fixes this. Let me know if you are still facing this issue.
